name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  build-linux-glibc217:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: "0.13.0"

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y upx-ucl
          cargo install cargo-zigbuild --locked

      - name: Build artifact
        run: bash ./build-linux-glibc217.sh

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: target/glibc217/logex
